# Creatin a web app that draw a graph by given input data
import tkinter as tk
import matplotlib.pyplot as plt
root = tk.Tk()
root.geometry("300x200")
root.config(bg="green")
canvas1 = tk.Canvas(root, width=450, height=750 , bg="white")
canvas1.pack(pady=20)
canvas1.place(x=10,y=5)
canvas2 = tk.Canvas(root, width=470, height=750 , bg="white")
canvas2.pack(pady=20)
canvas2.place(x=880,y=5)
canvas3 = tk.Canvas(root, width=350, height=100, bg="yellow")
canvas3.pack(pady=20)
canvas3.create_text(170,50, text="GRAPH's", fill="blue", font=("Times", 48, "bold"))
img1 = tk.PhotoImage(fil="im1.png")
img2 = tk.PhotoImage(fil="im2.png")
img3 = tk.PhotoImage(fil="img3.png")
img4 = tk.PhotoImage(fil="img4.png")
img1 = img1.zoom(2,2)
img2 = img2.zoom(2,2)
img3 = img3.zoom(2,2)
img4 = img4.zoom(2,2)
canvas1.create_image(200,180, image=img1)
canvas2.create_image(200,120, image=img2)
canvas2.create_image(240,500, image=img4)
canvas1.create_image(200,550, image=img3)
root.title("The Graph macker web app")
label1 = tk.Label(root, text="Lets make the graph")
label1.pack(pady=10)
label1.config(bg="yellow", fg="blue")
label2 = tk.Label(root, text="Enter the x coordinate data use comma to separate datas")
label2.pack(pady=10)
label2.config(bg="white", fg="black")
x = tk.Entry(root, width=30)
x.pack(pady=10)
x_label = tk.Label(root, text="Enter the title of x coordinate data")
x_label.pack(pady=10)
x_label.config(bg="yellow", fg="blue")
xlabel = tk.Entry(root, width=30)
xlabel.pack(pady=10)
label3 = tk.Label(root, text="Enter the y coordinate data use comma to separate datas")
label3.pack(pady=10)
y = tk.Entry(root, width=30)
y.pack(pady=10)
y_label = tk.Label(root, text="Enter the title of y coordinate data")
y_label.pack(pady=10)
y_label.config(bg="yellow", fg="blue")
ylabel = tk.Entry(root, width=30)
ylabel.pack(pady=10)
tit = tk.Label(root, text="Enter the title or name of the graph")
tit.pack(pady=10)
tit.config(bg="yellow", fg="blue")
title = tk.Entry(root, width= 30)
title.pack(pady=10)
# label4 = tk.Label(root, text="Which type of plot do you want to create enter the number according to the plot type\n1-for line plot\n2-for bar plot")
# label4.pack(pady=10)
# label4.config(bg="yellow", fg="blue")
# cmmond_enter= tk.Entry(root, width=30)
# cmmond_enter.pack(pady=10)
def graphp():
    x_data = [float(i) for i in x.get().split(",")]
    y_data = [float(j) for j in y.get().split(",")]
    plt.figure(figsize=(10,6))
    plt.plot(x_data, y_data)
    plt.xlabel(f"{xlabel.get()}".upper())
    plt.ylabel(f"{ylabel.get()}".upper())
    plt.title(f"{title.get()}")
    plt.grid(False)
    plt.tight_layout()
    plt.show()
def graphb():
    x_data = [float(i) for i in x.get().split(",")]
    y_data = [float(j) for j in y.get().split(",")]
    plt.figure(figsize=(10,6))
    plt.bar(x_data, y_data)
    plt.xlabel(f"{xlabel.get()}".upper())
    plt.ylabel(f"{ylabel.get()}".upper())
    plt.title(f"{title.get()}")
    plt.grid(False)
    plt.tight_layout()
    plt.show()
# def plot_selector():
#     option = cmmond_enter.get().strip()

#     if option == "1":
#         graphp()
#     elif option == "2":
#         graphb()
#     else:
#         print("Wrong option! Enter 1 or 2")

# code for clear the input and output where used .delete(0, tk.END) function and for matplotlib used close("all") function
def clear_all():
    x.delete(0, tk.END)
    y.delete(0, tk.END)
    xlabel.delete(0, tk.END)
    ylabel.delete(0, tk.END)
    title.delete(0, tk.END)
    plt.close('all')
# code for exit the program
def exit_app():
    root.destroy()
btn_frame = tk.Frame(root, bg="green")
btn_frame.pack(pady=15)
btn_frame1 = tk.Frame(root, bg="green")
btn_frame1.pack(pady=15)
clear_btn = tk.Button(btn_frame, text="Clear", width=10, command=clear_all)
clear_btn.grid(row=0, column=1, padx=5) # grid function is used to align the buttons therefor in program both clear and exit button are in one line
exit_btn = tk.Button(btn_frame, text="Exit", width=10, command=exit_app)
exit_btn.grid(row=0, column=2, padx=5)
button1 = tk.Button(btn_frame1, text="Plot line graph",command=graphp)
button1.grid(row=1, column=1, padx=5)
button2 = tk.Button(btn_frame1, text="Plot bar graph",command=graphb)
button2.grid(row=1, column=2, padx=5)
root.mainloop()

